### PR TITLE
Update dalle_playground_backend.ipynb

### LINKED ISSUE #63: SyntaxError: invalid syntax - line 3, app_port = 8000def app():
The colab worked a few days ago, but now gets an error when running the backend server.

image

### PR DESCRIPTION
**Pull request by trekkie1701c**
Add a Newline in the colab notebook; should fix  #63

### CODE REVIEW

**Review by the-garlic-os — APPROVED** [review]

**Comment by TyraelElDruin** [comment]
Can we get this merged so the docker file builds properly? Otherwise I'm going to have to fork and update the yaml or something 😭

**Comment by trekkie1701c** [comment]
> Can we get this merged so the docker file builds properly? Otherwise I'm going to have to fork and update the yaml or something sob

This won't fix the docker file, you'll want #61.  Which can just be implemented by editing the file on your local machine.

**Comment by TyraelElDruin** [comment]
@trekkie1701c thanks! You're absolutely right. I got it working in a forked repo. Appreciate the help!

**Comment by saharmor** [comment]
Thanks for flagging this! Got fixed as part of https://github.com/saharmor/dalle-playground/commit/83c27cef066f4130fe98dac8d1c41aadbd372cb5

**Pull request closed without merging**
