### PR TITLE
backend: save images as PNG instead of JPEG

### PR DESCRIPTION
**Pull request by withthelemons**

### CODE REVIEW

**Comment by saharmor** [comment]
Why changing to a png?

**Comment by oliverdevijt** [comment]
PNG is lossless, JPEG is lossy

**Comment by withthelemons** [comment]
The jpeg artifacts are quite visible and make further processing (eg. upscaling) harder.

**Comment by saharmor** [comment]
Thanks for opening this PR! I've added the option to specify the output image format in https://github.com/saharmor/dalle-playground/commit/cad1753193ed15c06c6dddc076d0f5d4a04653a7

**Pull request closed without merging**
