### PR TITLE
Update guide about how to run DALL-E Mega locally

### PR DESCRIPTION
**Pull request by haaakon**
Removed the link to an outdated Pull request and replaced with CLI arguments

### CODE REVIEW

**Comment by haaakon** [comment]
Seems like there are actually 3 different models to run
```
DALLE_MODEL_MINI = "dalle-mini/dalle-mini/mini-1:v0"  # the original DALL-E Mini. Fastest yet suboptimal results
DALLE_MODEL_MEGA = "dalle-mini/dalle-mini/mega-1-fp16:latest"  # the advanced version of DALL-E Mini. Requires more compute and VRAM
DALLE_MODEL_MEGA_FULL = "dalle-mini/dalle-mini/mega-1:latest"  # DALL-E Mega. Warning: requires significantly more storage and GPU RAM
```
Thir PR only lets the user set either mini or mega, should add a third option to run MEGA_FULL, but maybe rename that one to MEGA, and the current MEGA to MINI_ADVANCED or something? 
What do you think @saharmor

**Comment by DigitalDwagon** [comment]
The problem with mega_full was fixed with #29

**Comment by haaakon** [comment]
Updated the readme with the new parameter.

**Comment by zack6849** [comment]
Is mega_full heavier than mega? If you're going to keep the instructions saying to use mega_full, maybe change the title to reflect that, or just say to run with one of the different model sizes defined in the consts file, (mini, mega, mega_full) or something?

**Comment by saharmor** [comment]
Thanks for the contribution @haaakon and sorry for the belated response on this one. This should be addressed by the current readme, which got updated a few times since your PR. Feel free to reopen if still relevant.

**Pull request closed without merging**
